version: "3.6"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
  back:
    build:
      context: back
      dockerfile: Dockerfile
      target: development
    stdin_open: true
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back:/src
      - ./media:/media
    ports:
      - "$BACK_PORT:8000"
    depends_on:
      - db
      - selenium-hub
    links:
      - db
    environment:
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      SENDGRID_API_KEY: $SENDGRID_API_KEY
      ADMIN_EMAIL: $ADMIN_EMAIL
      DEFAULT_FROM_EMAIL: $DEFAULT_FROM_EMAIL
      SECRET_KEY: $SECRET_KEY
      DEBUG: $DEBUG
  selenium-hub:
    image: selenium/hub:4.1.0-20211209
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  firefox:
    image: selenium/node-firefox:4.1.0-20211209
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://localhost:4444
